builders:
  setPropsBuilder:
    import: 'package:props_generator_extension/props_generator_extension.dart'
    builder_factories: ['setPropsBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".info.part"]}
