name: props_generator_extension
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0-0 <3.0.0'

dependencies:
  source_gen: ^1.2.2
  props_generator_annotation:
    git:
      url: https://github.com/Olega95/setPropsGenerator.git
      path: props_generator_annotation
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  pedantic: ^1.10.0
  test: ^1.16.0
